version: '3.8'
services:
  
  elasticsearch:
    image: elasticsearch:${ELK_VERSION}
    container_name: elasticsearch
    hostname: elasticsearch
    restart: always
    volumes:
      - ./elastic/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elastic/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms1g"
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      TZ: Asia/Shanghai
      discovery.type: single-node
    networks:
      - devops
    extra_hosts:
      - "host.docker.internal:host-gateway"

  kibana:
    image: kibana:${ELK_VERSION}
    container_name: kibana
    hostname: kibana
    restart: always
    volumes:
      - ./elastic/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    environment:
      TZ: Asia/Shanghai
    networks:
      - devops
    depends_on:
      - elasticsearch
    extra_hosts:
      - "host.docker.internal:host-gateway"

  logstash:
    image: logstash:${ELK_VERSION}
    container_name: logstash
    hostname: logstash
    restart: always
    volumes:
      - ./elastic/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./elastic/logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./elastic/logstash/pipeline:/usr/share/logstash/pipeline
      - ${GEO_IP_PATH}:/usr/share/GeoIP
      - ${LOGS_PATH}:/var/log
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      TZ: Asia/Shanghai
      LS_JAVA_OPTS: "-Xmx2g -Xms2g"
    networks:
      - devops
    depends_on:
      - elasticsearch
    extra_hosts:
      - "host.docker.internal:host-gateway"

  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
    container_name: filebeat
    hostname: filebeat
    restart: always
    command: "filebeat -e -d *"
    volumes:
      - ./elastic/filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ${LOGS_PATH}:/var/log
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - devops
    extra_hosts:
      - "host.docker.internal:host-gateway"

  elasticview:
    image: kecikeci/elastic_view:latest
    container_name: elasticview
    hostname: elasticview
    restart: always
    volumes:
      - ./elastic/elasticview/data:/data
      - ./elastic/elasticview/logs:/logs
    ports:
      - "8090:8090"
    environment:
      TZ: Asia/Shanghai
    networks:
      - devops
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  devops:
    external: true
